language: ruby
rvm:
  - 2.2.3
  - 2.1.7
  - jruby-19mode
gemfile:
  - money-6.5.gemfile
  - money-6.6.gemfile
  - money-head.gemfile
sudo: false
notifications:
  disable: true
script: "bundle exec rake spec"
matrix:
  allow_failures:
    - gemfile: gemfiles/money-head.gemfile
  exclude:
    - rvm: jruby-19mode
      gemfile: money-head.gemfile
    - rvm: 2.1.7
      gemfile: money-head.gemfile
